version: 2.1
workflows:
    test-deploy:
        jobs:
            - test

jobs:
    test:
        docker:
            - image: cimg/node:20.17.0
              environment:
                  MONGODB_URI: mongodb://mongo:27017/test
                  PORT: 3000
            - image: mongo:4.4
              name: mongo
        steps:
            - checkout
            - run:
                  name: install deps
                  command: npm install
            - run:
                  name: start API in background
                  command: npm start &
                  background: true
            - run:
                  name: wait for MongoDB
                  command: dockerize -wait tcp://mongo:27017 -timeout 1m
            - run:
                  name: run tests
                  command: npm run test
